//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCMIContent.Web.TCMIContentServices {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Prayer", Namespace="http://tcmicrossroadcontent.apphb.com/")]
    [System.SerializableAttribute()]
    public partial class Prayer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConfidentialityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrayerRequestField;
        
        private System.DateTime ReceivedField;
        
        private int PrayedField;
        
        private bool AnsweredField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Confidentiality {
            get {
                return this.ConfidentialityField;
            }
            set {
                if ((object.ReferenceEquals(this.ConfidentialityField, value) != true)) {
                    this.ConfidentialityField = value;
                    this.RaisePropertyChanged("Confidentiality");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string PrayerRequest {
            get {
                return this.PrayerRequestField;
            }
            set {
                if ((object.ReferenceEquals(this.PrayerRequestField, value) != true)) {
                    this.PrayerRequestField = value;
                    this.RaisePropertyChanged("PrayerRequest");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.DateTime Received {
            get {
                return this.ReceivedField;
            }
            set {
                if ((this.ReceivedField.Equals(value) != true)) {
                    this.ReceivedField = value;
                    this.RaisePropertyChanged("Received");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int Prayed {
            get {
                return this.PrayedField;
            }
            set {
                if ((this.PrayedField.Equals(value) != true)) {
                    this.PrayedField = value;
                    this.RaisePropertyChanged("Prayed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public bool Answered {
            get {
                return this.AnsweredField;
            }
            set {
                if ((this.AnsweredField.Equals(value) != true)) {
                    this.AnsweredField = value;
                    this.RaisePropertyChanged("Answered");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tcmicrossroadcontent.apphb.com/", ConfigurationName="TCMIContentServices.TCMIContentSoap")]
    public interface TCMIContentSoap {
        
        // CODEGEN: Generating message contract since element name name from namespace http://tcmicrossroadcontent.apphb.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tcmicrossroadcontent.apphb.com/AddPrayer", ReplyAction="*")]
        TCMIContent.Web.TCMIContentServices.AddPrayerResponse AddPrayer(TCMIContent.Web.TCMIContentServices.AddPrayerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tcmicrossroadcontent.apphb.com/AddPrayer", ReplyAction="*")]
        System.Threading.Tasks.Task<TCMIContent.Web.TCMIContentServices.AddPrayerResponse> AddPrayerAsync(TCMIContent.Web.TCMIContentServices.AddPrayerRequest request);
        
        // CODEGEN: Generating message contract since element name name from namespace http://tcmicrossroadcontent.apphb.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tcmicrossroadcontent.apphb.com/UpdatePrayer", ReplyAction="*")]
        TCMIContent.Web.TCMIContentServices.UpdatePrayerResponse UpdatePrayer(TCMIContent.Web.TCMIContentServices.UpdatePrayerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tcmicrossroadcontent.apphb.com/UpdatePrayer", ReplyAction="*")]
        System.Threading.Tasks.Task<TCMIContent.Web.TCMIContentServices.UpdatePrayerResponse> UpdatePrayerAsync(TCMIContent.Web.TCMIContentServices.UpdatePrayerRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (UpdatePrayed) of message UpdatePrayed does not match the default value (UpdatePrayer1)
        [System.ServiceModel.OperationContractAttribute(Action="http://tcmicrossroadcontent.apphb.com/UpdatePrayed", ReplyAction="*")]
        TCMIContent.Web.TCMIContentServices.UpdatePrayed1 UpdatePrayer1(TCMIContent.Web.TCMIContentServices.UpdatePrayed request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tcmicrossroadcontent.apphb.com/UpdatePrayed", ReplyAction="*")]
        System.Threading.Tasks.Task<TCMIContent.Web.TCMIContentServices.UpdatePrayed1> UpdatePrayer1Async(TCMIContent.Web.TCMIContentServices.UpdatePrayed request);
        
        // CODEGEN: Generating message contract since element name AnsweredPrayerResult from namespace http://tcmicrossroadcontent.apphb.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tcmicrossroadcontent.apphb.com/AnsweredPrayer", ReplyAction="*")]
        TCMIContent.Web.TCMIContentServices.AnsweredPrayerResponse AnsweredPrayer(TCMIContent.Web.TCMIContentServices.AnsweredPrayerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tcmicrossroadcontent.apphb.com/AnsweredPrayer", ReplyAction="*")]
        System.Threading.Tasks.Task<TCMIContent.Web.TCMIContentServices.AnsweredPrayerResponse> AnsweredPrayerAsync(TCMIContent.Web.TCMIContentServices.AnsweredPrayerRequest request);
        
        // CODEGEN: Generating message contract since element name PrayedResult from namespace http://tcmicrossroadcontent.apphb.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tcmicrossroadcontent.apphb.com/Prayed", ReplyAction="*")]
        TCMIContent.Web.TCMIContentServices.PrayedResponse Prayed(TCMIContent.Web.TCMIContentServices.PrayedRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tcmicrossroadcontent.apphb.com/Prayed", ReplyAction="*")]
        System.Threading.Tasks.Task<TCMIContent.Web.TCMIContentServices.PrayedResponse> PrayedAsync(TCMIContent.Web.TCMIContentServices.PrayedRequest request);
        
        // CODEGEN: Generating message contract since element name GetPrayersResult from namespace http://tcmicrossroadcontent.apphb.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tcmicrossroadcontent.apphb.com/GetPrayers", ReplyAction="*")]
        TCMIContent.Web.TCMIContentServices.GetPrayersResponse GetPrayers(TCMIContent.Web.TCMIContentServices.GetPrayersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tcmicrossroadcontent.apphb.com/GetPrayers", ReplyAction="*")]
        System.Threading.Tasks.Task<TCMIContent.Web.TCMIContentServices.GetPrayersResponse> GetPrayersAsync(TCMIContent.Web.TCMIContentServices.GetPrayersRequest request);
        
        // CODEGEN: Generating message contract since element name RemovePrayerResult from namespace http://tcmicrossroadcontent.apphb.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tcmicrossroadcontent.apphb.com/RemovePrayer", ReplyAction="*")]
        TCMIContent.Web.TCMIContentServices.RemovePrayerResponse RemovePrayer(TCMIContent.Web.TCMIContentServices.RemovePrayerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tcmicrossroadcontent.apphb.com/RemovePrayer", ReplyAction="*")]
        System.Threading.Tasks.Task<TCMIContent.Web.TCMIContentServices.RemovePrayerResponse> RemovePrayerAsync(TCMIContent.Web.TCMIContentServices.RemovePrayerRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddPrayerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddPrayer", Namespace="http://tcmicrossroadcontent.apphb.com/", Order=0)]
        public TCMIContent.Web.TCMIContentServices.AddPrayerRequestBody Body;
        
        public AddPrayerRequest() {
        }
        
        public AddPrayerRequest(TCMIContent.Web.TCMIContentServices.AddPrayerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tcmicrossroadcontent.apphb.com/")]
    public partial class AddPrayerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string phone;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string confidential;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string request;
        
        public AddPrayerRequestBody() {
        }
        
        public AddPrayerRequestBody(string name, string email, string phone, string confidential, string request) {
            this.name = name;
            this.email = email;
            this.phone = phone;
            this.confidential = confidential;
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddPrayerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddPrayerResponse", Namespace="http://tcmicrossroadcontent.apphb.com/", Order=0)]
        public TCMIContent.Web.TCMIContentServices.AddPrayerResponseBody Body;
        
        public AddPrayerResponse() {
        }
        
        public AddPrayerResponse(TCMIContent.Web.TCMIContentServices.AddPrayerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tcmicrossroadcontent.apphb.com/")]
    public partial class AddPrayerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddPrayerResult;
        
        public AddPrayerResponseBody() {
        }
        
        public AddPrayerResponseBody(string AddPrayerResult) {
            this.AddPrayerResult = AddPrayerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdatePrayerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdatePrayer", Namespace="http://tcmicrossroadcontent.apphb.com/", Order=0)]
        public TCMIContent.Web.TCMIContentServices.UpdatePrayerRequestBody Body;
        
        public UpdatePrayerRequest() {
        }
        
        public UpdatePrayerRequest(TCMIContent.Web.TCMIContentServices.UpdatePrayerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tcmicrossroadcontent.apphb.com/")]
    public partial class UpdatePrayerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string phone;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string confidential;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string request;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int prayed;
        
        public UpdatePrayerRequestBody() {
        }
        
        public UpdatePrayerRequestBody(int id, string name, string email, string phone, string confidential, string request, int prayed) {
            this.id = id;
            this.name = name;
            this.email = email;
            this.phone = phone;
            this.confidential = confidential;
            this.request = request;
            this.prayed = prayed;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdatePrayerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdatePrayerResponse", Namespace="http://tcmicrossroadcontent.apphb.com/", Order=0)]
        public TCMIContent.Web.TCMIContentServices.UpdatePrayerResponseBody Body;
        
        public UpdatePrayerResponse() {
        }
        
        public UpdatePrayerResponse(TCMIContent.Web.TCMIContentServices.UpdatePrayerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tcmicrossroadcontent.apphb.com/")]
    public partial class UpdatePrayerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UpdatePrayerResult;
        
        public UpdatePrayerResponseBody() {
        }
        
        public UpdatePrayerResponseBody(string UpdatePrayerResult) {
            this.UpdatePrayerResult = UpdatePrayerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdatePrayed", WrapperNamespace="http://tcmicrossroadcontent.apphb.com/", IsWrapped=true)]
    public partial class UpdatePrayed {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tcmicrossroadcontent.apphb.com/", Order=0)]
        public int id;
        
        public UpdatePrayed() {
        }
        
        public UpdatePrayed(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdatePrayedResponse", WrapperNamespace="http://tcmicrossroadcontent.apphb.com/", IsWrapped=true)]
    public partial class UpdatePrayed1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tcmicrossroadcontent.apphb.com/", Order=0)]
        public string UpdatePrayedResult;
        
        public UpdatePrayed1() {
        }
        
        public UpdatePrayed1(string UpdatePrayedResult) {
            this.UpdatePrayedResult = UpdatePrayedResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AnsweredPrayerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AnsweredPrayer", Namespace="http://tcmicrossroadcontent.apphb.com/", Order=0)]
        public TCMIContent.Web.TCMIContentServices.AnsweredPrayerRequestBody Body;
        
        public AnsweredPrayerRequest() {
        }
        
        public AnsweredPrayerRequest(TCMIContent.Web.TCMIContentServices.AnsweredPrayerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tcmicrossroadcontent.apphb.com/")]
    public partial class AnsweredPrayerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public AnsweredPrayerRequestBody() {
        }
        
        public AnsweredPrayerRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AnsweredPrayerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AnsweredPrayerResponse", Namespace="http://tcmicrossroadcontent.apphb.com/", Order=0)]
        public TCMIContent.Web.TCMIContentServices.AnsweredPrayerResponseBody Body;
        
        public AnsweredPrayerResponse() {
        }
        
        public AnsweredPrayerResponse(TCMIContent.Web.TCMIContentServices.AnsweredPrayerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tcmicrossroadcontent.apphb.com/")]
    public partial class AnsweredPrayerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AnsweredPrayerResult;
        
        public AnsweredPrayerResponseBody() {
        }
        
        public AnsweredPrayerResponseBody(string AnsweredPrayerResult) {
            this.AnsweredPrayerResult = AnsweredPrayerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PrayedRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Prayed", Namespace="http://tcmicrossroadcontent.apphb.com/", Order=0)]
        public TCMIContent.Web.TCMIContentServices.PrayedRequestBody Body;
        
        public PrayedRequest() {
        }
        
        public PrayedRequest(TCMIContent.Web.TCMIContentServices.PrayedRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tcmicrossroadcontent.apphb.com/")]
    public partial class PrayedRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public PrayedRequestBody() {
        }
        
        public PrayedRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PrayedResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PrayedResponse", Namespace="http://tcmicrossroadcontent.apphb.com/", Order=0)]
        public TCMIContent.Web.TCMIContentServices.PrayedResponseBody Body;
        
        public PrayedResponse() {
        }
        
        public PrayedResponse(TCMIContent.Web.TCMIContentServices.PrayedResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tcmicrossroadcontent.apphb.com/")]
    public partial class PrayedResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PrayedResult;
        
        public PrayedResponseBody() {
        }
        
        public PrayedResponseBody(string PrayedResult) {
            this.PrayedResult = PrayedResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPrayersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPrayers", Namespace="http://tcmicrossroadcontent.apphb.com/", Order=0)]
        public TCMIContent.Web.TCMIContentServices.GetPrayersRequestBody Body;
        
        public GetPrayersRequest() {
        }
        
        public GetPrayersRequest(TCMIContent.Web.TCMIContentServices.GetPrayersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetPrayersRequestBody {
        
        public GetPrayersRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPrayersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPrayersResponse", Namespace="http://tcmicrossroadcontent.apphb.com/", Order=0)]
        public TCMIContent.Web.TCMIContentServices.GetPrayersResponseBody Body;
        
        public GetPrayersResponse() {
        }
        
        public GetPrayersResponse(TCMIContent.Web.TCMIContentServices.GetPrayersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tcmicrossroadcontent.apphb.com/")]
    public partial class GetPrayersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TCMIContent.Web.TCMIContentServices.Prayer[] GetPrayersResult;
        
        public GetPrayersResponseBody() {
        }
        
        public GetPrayersResponseBody(TCMIContent.Web.TCMIContentServices.Prayer[] GetPrayersResult) {
            this.GetPrayersResult = GetPrayersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemovePrayerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RemovePrayer", Namespace="http://tcmicrossroadcontent.apphb.com/", Order=0)]
        public TCMIContent.Web.TCMIContentServices.RemovePrayerRequestBody Body;
        
        public RemovePrayerRequest() {
        }
        
        public RemovePrayerRequest(TCMIContent.Web.TCMIContentServices.RemovePrayerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tcmicrossroadcontent.apphb.com/")]
    public partial class RemovePrayerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public RemovePrayerRequestBody() {
        }
        
        public RemovePrayerRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemovePrayerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RemovePrayerResponse", Namespace="http://tcmicrossroadcontent.apphb.com/", Order=0)]
        public TCMIContent.Web.TCMIContentServices.RemovePrayerResponseBody Body;
        
        public RemovePrayerResponse() {
        }
        
        public RemovePrayerResponse(TCMIContent.Web.TCMIContentServices.RemovePrayerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tcmicrossroadcontent.apphb.com/")]
    public partial class RemovePrayerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RemovePrayerResult;
        
        public RemovePrayerResponseBody() {
        }
        
        public RemovePrayerResponseBody(string RemovePrayerResult) {
            this.RemovePrayerResult = RemovePrayerResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TCMIContentSoapChannel : TCMIContent.Web.TCMIContentServices.TCMIContentSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TCMIContentSoapClient : System.ServiceModel.ClientBase<TCMIContent.Web.TCMIContentServices.TCMIContentSoap>, TCMIContent.Web.TCMIContentServices.TCMIContentSoap {
        
        public TCMIContentSoapClient() {
        }
        
        public TCMIContentSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TCMIContentSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TCMIContentSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TCMIContentSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TCMIContent.Web.TCMIContentServices.AddPrayerResponse TCMIContent.Web.TCMIContentServices.TCMIContentSoap.AddPrayer(TCMIContent.Web.TCMIContentServices.AddPrayerRequest request) {
            return base.Channel.AddPrayer(request);
        }
        
        public string AddPrayer(string name, string email, string phone, string confidential, string request) {
            TCMIContent.Web.TCMIContentServices.AddPrayerRequest inValue = new TCMIContent.Web.TCMIContentServices.AddPrayerRequest();
            inValue.Body = new TCMIContent.Web.TCMIContentServices.AddPrayerRequestBody();
            inValue.Body.name = name;
            inValue.Body.email = email;
            inValue.Body.phone = phone;
            inValue.Body.confidential = confidential;
            inValue.Body.request = request;
            TCMIContent.Web.TCMIContentServices.AddPrayerResponse retVal = ((TCMIContent.Web.TCMIContentServices.TCMIContentSoap)(this)).AddPrayer(inValue);
            return retVal.Body.AddPrayerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TCMIContent.Web.TCMIContentServices.AddPrayerResponse> TCMIContent.Web.TCMIContentServices.TCMIContentSoap.AddPrayerAsync(TCMIContent.Web.TCMIContentServices.AddPrayerRequest request) {
            return base.Channel.AddPrayerAsync(request);
        }
        
        public System.Threading.Tasks.Task<TCMIContent.Web.TCMIContentServices.AddPrayerResponse> AddPrayerAsync(string name, string email, string phone, string confidential, string request) {
            TCMIContent.Web.TCMIContentServices.AddPrayerRequest inValue = new TCMIContent.Web.TCMIContentServices.AddPrayerRequest();
            inValue.Body = new TCMIContent.Web.TCMIContentServices.AddPrayerRequestBody();
            inValue.Body.name = name;
            inValue.Body.email = email;
            inValue.Body.phone = phone;
            inValue.Body.confidential = confidential;
            inValue.Body.request = request;
            return ((TCMIContent.Web.TCMIContentServices.TCMIContentSoap)(this)).AddPrayerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TCMIContent.Web.TCMIContentServices.UpdatePrayerResponse TCMIContent.Web.TCMIContentServices.TCMIContentSoap.UpdatePrayer(TCMIContent.Web.TCMIContentServices.UpdatePrayerRequest request) {
            return base.Channel.UpdatePrayer(request);
        }
        
        public string UpdatePrayer(int id, string name, string email, string phone, string confidential, string request, int prayed) {
            TCMIContent.Web.TCMIContentServices.UpdatePrayerRequest inValue = new TCMIContent.Web.TCMIContentServices.UpdatePrayerRequest();
            inValue.Body = new TCMIContent.Web.TCMIContentServices.UpdatePrayerRequestBody();
            inValue.Body.id = id;
            inValue.Body.name = name;
            inValue.Body.email = email;
            inValue.Body.phone = phone;
            inValue.Body.confidential = confidential;
            inValue.Body.request = request;
            inValue.Body.prayed = prayed;
            TCMIContent.Web.TCMIContentServices.UpdatePrayerResponse retVal = ((TCMIContent.Web.TCMIContentServices.TCMIContentSoap)(this)).UpdatePrayer(inValue);
            return retVal.Body.UpdatePrayerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TCMIContent.Web.TCMIContentServices.UpdatePrayerResponse> TCMIContent.Web.TCMIContentServices.TCMIContentSoap.UpdatePrayerAsync(TCMIContent.Web.TCMIContentServices.UpdatePrayerRequest request) {
            return base.Channel.UpdatePrayerAsync(request);
        }
        
        public System.Threading.Tasks.Task<TCMIContent.Web.TCMIContentServices.UpdatePrayerResponse> UpdatePrayerAsync(int id, string name, string email, string phone, string confidential, string request, int prayed) {
            TCMIContent.Web.TCMIContentServices.UpdatePrayerRequest inValue = new TCMIContent.Web.TCMIContentServices.UpdatePrayerRequest();
            inValue.Body = new TCMIContent.Web.TCMIContentServices.UpdatePrayerRequestBody();
            inValue.Body.id = id;
            inValue.Body.name = name;
            inValue.Body.email = email;
            inValue.Body.phone = phone;
            inValue.Body.confidential = confidential;
            inValue.Body.request = request;
            inValue.Body.prayed = prayed;
            return ((TCMIContent.Web.TCMIContentServices.TCMIContentSoap)(this)).UpdatePrayerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TCMIContent.Web.TCMIContentServices.UpdatePrayed1 TCMIContent.Web.TCMIContentServices.TCMIContentSoap.UpdatePrayer1(TCMIContent.Web.TCMIContentServices.UpdatePrayed request) {
            return base.Channel.UpdatePrayer1(request);
        }
        
        public string UpdatePrayer1(int id) {
            TCMIContent.Web.TCMIContentServices.UpdatePrayed inValue = new TCMIContent.Web.TCMIContentServices.UpdatePrayed();
            inValue.id = id;
            TCMIContent.Web.TCMIContentServices.UpdatePrayed1 retVal = ((TCMIContent.Web.TCMIContentServices.TCMIContentSoap)(this)).UpdatePrayer1(inValue);
            return retVal.UpdatePrayedResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TCMIContent.Web.TCMIContentServices.UpdatePrayed1> TCMIContent.Web.TCMIContentServices.TCMIContentSoap.UpdatePrayer1Async(TCMIContent.Web.TCMIContentServices.UpdatePrayed request) {
            return base.Channel.UpdatePrayer1Async(request);
        }
        
        public System.Threading.Tasks.Task<TCMIContent.Web.TCMIContentServices.UpdatePrayed1> UpdatePrayer1Async(int id) {
            TCMIContent.Web.TCMIContentServices.UpdatePrayed inValue = new TCMIContent.Web.TCMIContentServices.UpdatePrayed();
            inValue.id = id;
            return ((TCMIContent.Web.TCMIContentServices.TCMIContentSoap)(this)).UpdatePrayer1Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TCMIContent.Web.TCMIContentServices.AnsweredPrayerResponse TCMIContent.Web.TCMIContentServices.TCMIContentSoap.AnsweredPrayer(TCMIContent.Web.TCMIContentServices.AnsweredPrayerRequest request) {
            return base.Channel.AnsweredPrayer(request);
        }
        
        public string AnsweredPrayer(int id) {
            TCMIContent.Web.TCMIContentServices.AnsweredPrayerRequest inValue = new TCMIContent.Web.TCMIContentServices.AnsweredPrayerRequest();
            inValue.Body = new TCMIContent.Web.TCMIContentServices.AnsweredPrayerRequestBody();
            inValue.Body.id = id;
            TCMIContent.Web.TCMIContentServices.AnsweredPrayerResponse retVal = ((TCMIContent.Web.TCMIContentServices.TCMIContentSoap)(this)).AnsweredPrayer(inValue);
            return retVal.Body.AnsweredPrayerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TCMIContent.Web.TCMIContentServices.AnsweredPrayerResponse> TCMIContent.Web.TCMIContentServices.TCMIContentSoap.AnsweredPrayerAsync(TCMIContent.Web.TCMIContentServices.AnsweredPrayerRequest request) {
            return base.Channel.AnsweredPrayerAsync(request);
        }
        
        public System.Threading.Tasks.Task<TCMIContent.Web.TCMIContentServices.AnsweredPrayerResponse> AnsweredPrayerAsync(int id) {
            TCMIContent.Web.TCMIContentServices.AnsweredPrayerRequest inValue = new TCMIContent.Web.TCMIContentServices.AnsweredPrayerRequest();
            inValue.Body = new TCMIContent.Web.TCMIContentServices.AnsweredPrayerRequestBody();
            inValue.Body.id = id;
            return ((TCMIContent.Web.TCMIContentServices.TCMIContentSoap)(this)).AnsweredPrayerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TCMIContent.Web.TCMIContentServices.PrayedResponse TCMIContent.Web.TCMIContentServices.TCMIContentSoap.Prayed(TCMIContent.Web.TCMIContentServices.PrayedRequest request) {
            return base.Channel.Prayed(request);
        }
        
        public string Prayed(int id) {
            TCMIContent.Web.TCMIContentServices.PrayedRequest inValue = new TCMIContent.Web.TCMIContentServices.PrayedRequest();
            inValue.Body = new TCMIContent.Web.TCMIContentServices.PrayedRequestBody();
            inValue.Body.id = id;
            TCMIContent.Web.TCMIContentServices.PrayedResponse retVal = ((TCMIContent.Web.TCMIContentServices.TCMIContentSoap)(this)).Prayed(inValue);
            return retVal.Body.PrayedResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TCMIContent.Web.TCMIContentServices.PrayedResponse> TCMIContent.Web.TCMIContentServices.TCMIContentSoap.PrayedAsync(TCMIContent.Web.TCMIContentServices.PrayedRequest request) {
            return base.Channel.PrayedAsync(request);
        }
        
        public System.Threading.Tasks.Task<TCMIContent.Web.TCMIContentServices.PrayedResponse> PrayedAsync(int id) {
            TCMIContent.Web.TCMIContentServices.PrayedRequest inValue = new TCMIContent.Web.TCMIContentServices.PrayedRequest();
            inValue.Body = new TCMIContent.Web.TCMIContentServices.PrayedRequestBody();
            inValue.Body.id = id;
            return ((TCMIContent.Web.TCMIContentServices.TCMIContentSoap)(this)).PrayedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TCMIContent.Web.TCMIContentServices.GetPrayersResponse TCMIContent.Web.TCMIContentServices.TCMIContentSoap.GetPrayers(TCMIContent.Web.TCMIContentServices.GetPrayersRequest request) {
            return base.Channel.GetPrayers(request);
        }
        
        public TCMIContent.Web.TCMIContentServices.Prayer[] GetPrayers() {
            TCMIContent.Web.TCMIContentServices.GetPrayersRequest inValue = new TCMIContent.Web.TCMIContentServices.GetPrayersRequest();
            inValue.Body = new TCMIContent.Web.TCMIContentServices.GetPrayersRequestBody();
            TCMIContent.Web.TCMIContentServices.GetPrayersResponse retVal = ((TCMIContent.Web.TCMIContentServices.TCMIContentSoap)(this)).GetPrayers(inValue);
            return retVal.Body.GetPrayersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TCMIContent.Web.TCMIContentServices.GetPrayersResponse> TCMIContent.Web.TCMIContentServices.TCMIContentSoap.GetPrayersAsync(TCMIContent.Web.TCMIContentServices.GetPrayersRequest request) {
            return base.Channel.GetPrayersAsync(request);
        }
        
        public System.Threading.Tasks.Task<TCMIContent.Web.TCMIContentServices.GetPrayersResponse> GetPrayersAsync() {
            TCMIContent.Web.TCMIContentServices.GetPrayersRequest inValue = new TCMIContent.Web.TCMIContentServices.GetPrayersRequest();
            inValue.Body = new TCMIContent.Web.TCMIContentServices.GetPrayersRequestBody();
            return ((TCMIContent.Web.TCMIContentServices.TCMIContentSoap)(this)).GetPrayersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TCMIContent.Web.TCMIContentServices.RemovePrayerResponse TCMIContent.Web.TCMIContentServices.TCMIContentSoap.RemovePrayer(TCMIContent.Web.TCMIContentServices.RemovePrayerRequest request) {
            return base.Channel.RemovePrayer(request);
        }
        
        public string RemovePrayer(int id) {
            TCMIContent.Web.TCMIContentServices.RemovePrayerRequest inValue = new TCMIContent.Web.TCMIContentServices.RemovePrayerRequest();
            inValue.Body = new TCMIContent.Web.TCMIContentServices.RemovePrayerRequestBody();
            inValue.Body.id = id;
            TCMIContent.Web.TCMIContentServices.RemovePrayerResponse retVal = ((TCMIContent.Web.TCMIContentServices.TCMIContentSoap)(this)).RemovePrayer(inValue);
            return retVal.Body.RemovePrayerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TCMIContent.Web.TCMIContentServices.RemovePrayerResponse> TCMIContent.Web.TCMIContentServices.TCMIContentSoap.RemovePrayerAsync(TCMIContent.Web.TCMIContentServices.RemovePrayerRequest request) {
            return base.Channel.RemovePrayerAsync(request);
        }
        
        public System.Threading.Tasks.Task<TCMIContent.Web.TCMIContentServices.RemovePrayerResponse> RemovePrayerAsync(int id) {
            TCMIContent.Web.TCMIContentServices.RemovePrayerRequest inValue = new TCMIContent.Web.TCMIContentServices.RemovePrayerRequest();
            inValue.Body = new TCMIContent.Web.TCMIContentServices.RemovePrayerRequestBody();
            inValue.Body.id = id;
            return ((TCMIContent.Web.TCMIContentServices.TCMIContentSoap)(this)).RemovePrayerAsync(inValue);
        }
    }
}
